### ISSUE TITLE
Refactor variable names in Square.js

### ISSUE THREAD

**Issue by thuyanduong** [segunsub/tic-tac#3]
What is this line of code? `const count = useSelector(currentBoard);`

There should be **NO MENTION** of `count` in your app. You are not making a counter application. 

It should be something like `const state = useSelector(currentBoard);`

Next, refactor your property names to be camelCase:
`count.TicTac[props.sqr] === null && !count.GameOver.gameOver` should be `state.board[props.sqr] === null && !state.gameOverSlice.gameOver`

Finally, it is a bad practice to use `store.getState()`. Remove all instances of `store.getState()` because you should be able to use the return value of `useSelector` to access your redux state!

**Comment by segunsub** [comment]
I don't get the updated state with useSelector

**Comment by thuyanduong** [comment]
The code looks good now
